---
title: "CAZY MSP"
output: html_notebook
---




## Load library

```{r, message=FALSE, warning=FALSE}

library(dplyr)
library(magrittr)
library(ggplot2)
library(vegan)

devtools::load_all()


library(IBSMicrobiota)

```

## MSP wrangling

the aim here is to summarize the count data to MSP

```{r}


data("MSP_tax")
data("MSP_genes_id_corresp")







```


## Load CAZy annotation


```{r connect_db}


## connect to the metahit database



metahit.sqlite.db <- src_sqlite("/opt/sqlite/metahit.v2.sqlite.db")
#metahit.sqlite.db <- src_sqlite("/lustre/samba/samba_write/tapj/metahit.v2.sqlite.db")



# list table in DB
#dbListTables(metahit.sqlite.db)




#extract tbl in dplyr format
#kegg_sqlite <- tbl(metahit.sqlite.db, "kegg")
#cag_sqlite  <- tbl(metahit.sqlite.db, "cag")
cazy_sqlite <- tbl(metahit.sqlite.db, "cazy")
#og_sqlite   <- tbl(metahit.sqlite.db, "og")



```



## correponsance MSP and CAZY



```{r}



MSP_CAZY_df =
MSP_genes_id_corresp %>%
  merge(.,cazy_sqlite, by.x="gene_name_v2", by.y="genes_id")

MSP_CAZY_df %>% head
  
write.csv2(MSP_CAZY_df,file="MSP_CAZY_df.csv")


```



## explore
```{r}


MSP_CAZY_df %>%
  filter(cazy.family%in% c("CBM32","GH2")) %>%
  group_by(msp_name,cazy.family) %>%
  summarise(n=n()) %>%
  reshape2::dcast(msp_name~cazy.family, value.var="n", fill = 0) %>%
  ggplot() + geom_point(aes(x=GH2,y=CBM32)) #+ scale_y_log10() + scale_x_log10()







```


# export cazy MSP count rescaled
```{r}


counts_rescaled %>% 
  merge(., MSP_genes_id_corresp %>% select(msp_name,module_name,gene_name_v2), by.x="genes.id", by.y="gene_name_v2",all=FALSE) %>% 
  merge(., cazy_sqlite, by.y="genes_id", by.x="genes.id", all=FALSE) %>%
  select(-genes.id,-length,-module_name) -> MSP_cazy_df



# MSP_KO_df %>%
#   reshape2::melt(id.vars=c("msp_name","KO")) %>%
#   filter(value>0)-> MSP_KO_df_melt
# 
# write.csv2(MSP_KO_df_melt, file = "MSP_KO_df_melt.csv")


MSP_cazy_df %>% 
  select(-row_names) %>%
  group_by(msp_name,cazy_family) %>%
  summarise_all(sum) -> MSP_cazy_counts

write.csv2(MSP_cazy_counts, file="MSP_cazy_counts.csv")

```


