---
title: "explore infraspecies"
output: html_notebook
---




## Load library

```{r, message=FALSE, warning=FALSE}

library(dplyr)
library(magrittr)
library(ggplot2)

devtools::load_all()


library(IBSMicrobiota)

```

## MSP wrangling

the aim here is to summarize the count data to MSP

```{r}

data("hs3_9.genes_length")
data("counts")
data("MSP_tax")
data("MSP_genes_id_corresp")



counts %>% head



```


### Normalize by gene length and read count

```{r}

merge(counts, hs3_9.genes_length, by.x="id_fragment", by.y="row.names") %>%
  select(-id_fragment, -id_fragment_external, -sample_count) -> counts


cols = grep("M", colnames(counts), value=TRUE)

total_reads = apply(counts[cols],2,sum)

remove_sample = which(total_reads < 1000000) %>% names



counts[cols] = lapply(counts[cols], `/`, counts$length) 


#


#counts_rescaled = counts %>% select(-one_of(remove_sample))

counts[cols] = prop.table(counts[cols] %>% as.matrix ,2)

counts_rescaled = counts

counts_rescaled[cols] = counts_rescaled[cols] %>% t %>% multiply_by(total_reads %>% as.numeric ) %>% t %>% round()


counts = counts %>% select(-one_of(remove_sample))

#cols_remove_sample = cols[-remove_sample]

#which(cols == "M066")

#which(counts %>% colnames == "M066")

```


### MSP counts correspondance

```{r, message=FALSE, warning=FALSE}
#merge(counts %>% head(1000), MSP_genes_id_corresp %>% select(msp_name,module_name,gene_name_v2), by.x="genes.id", by.y="gene_name_v2")

# an example with inbuilt function
merge(counts_rescaled, 
      MSP_genes_id_corresp %>% 
        select(msp_name,module_name,gene_name_v2) %>% 
        filter(msp_name %in% c("msp_0079")),
      by.x="genes.id", by.y="gene_name_v2") -> msp_counts

binarize_MSP(msp_counts=msp_counts, cutoff_med = 10) -> binary_msp

```



### import infraspecies table

```{r, message=FALSE, warning=FALSE}

infraspecies = readr::read_csv2(system.file("infraspecies", "infraspecies_table_full.csv", package="IBSFood"))[,-1]

infraspecies %>% head



```



### MSP binary and infraspecies


```{r}

msp_target="msp_0070"

infraspecies %>%
  filter(msp_name == msp_target) %>%
  select(species,genus,family)


merge(counts_rescaled, 
      MSP_genes_id_corresp %>% 
        select(msp_name,module_name,gene_name_v2) %>% 
        filter(msp_name %in% c(msp_target)),
      by.x="genes.id", by.y="gene_name_v2") -> msp_counts

binarize_MSP(msp_counts=msp_counts, cutoff_med = 10) -> binary_msp


infraspecies %>%
  filter(msp_name == msp_target) %>%
  select(contains("M"), msp_name, msp_name_partition) %>%
  reshape2::melt(id.vars=c("msp_name","msp_name_partition")) %>%
  group_by(variable) %>%
  top_n(1, wt = value ) %>%
  rename(partition = msp_name_partition)  -> clusters_msp



#binary_msp %>% colnames


#test_MSP_gene(binary_msp = binary_msp, clusters_msp = clusters_msp)


binary_msp %>%
  filter(module_name != "core") %>%
  reshape2::melt(id.vars=c("genes.id","module_name")) %>%
  merge(., clusters_msp,
        by=c("variable")) %>%
  group_by(genes.id) %>%
  mutate(s=sum(value.x),l=length(value.x)) %>%
  filter(s>0, s<l) %>%
  do(w = with(.,suppressWarnings(chisq.test(partition,value.x,simulate.p.value = FALSE))  )) %>%
  broom::tidy(w) %>%
  ungroup() %>%
  mutate(fdr=p.adjust(p.value, method="fdr")) %>%
  filter(fdr<0.05) %>%
  select(genes.id,p.value,fdr) -> test_msp


partitionize_MSP(binary_msp=binary_msp) -> clusters_msp


plot_MSP(binary_msp=binary_msp, 
         clusters_msp=clusters_msp$sample, 
         clusters_msp_gene = clusters_msp$gene)

ggsave("msp_0070.pdf")


test_MSP_gene(binary_msp=binary_msp, 
         clusters_msp=clusters_msp$sample) -> test_msp



  test_msp %>%
    filter(fdr<0.05) %>%
    left_join(binary_msp) %>%
    #head %>%
    select(-p.value,-fdr,-module_name) %>%
    reshape2::melt(id.vars="genes.id") %>%
    merge(clusters_msp$sample$partition %>% as.matrix %>% as.data.frame() , by.y = "row.names", by.x="variable" ) %>%
    #reshape2::dcast(genes.id~variable+V1, value.var="value") %>%
    ggplot() + geom_tile(aes(x=genes.id,y=variable, fill=value %>% as.character)) + 
    facet_grid(~V1, scales = "free_x") + ylab("") +
    theme(axis.text = element_blank()) + coord_flip() + guides(fill=FALSE) + scale_fill_manual(values = c("black","yellow"))
  
ggsave("msp_0070_diff.pdf")  
  
  
```



```{r}

metahit.sqlite.db = src_sqlite("/tmp/metahit.v2.sqlite.db")

kegg_sqlite = tbl(metahit.sqlite.db, "kegg")

cazy_sqlite = tbl(metahit.sqlite.db, "cazy")


test_msp %>% 
  filter(fdr<0.05) %>%
  dplyr::rename(genes_id = `genes.id`) %>%
  left_join(kegg_sqlite,  copy=TRUE ) %>%
  left_join(cazy_sqlite,  copy=TRUE ) %>%
  arrange(genes_id) %>%
  filter(!is.na(KO) | !is.na(cazy_family))




```









