---
title: "Figure food tree"
output: html_notebook
---


```{r}
library(ggplot2)
library(phyloseq)
library(dplyr)
library(magrittr)
library(tidygraph)
library(ggraph)
devtools::load_all()


```



```{r fig.height=10, fig.width=10}
data("food_group_levels")

food_group_levels %>% filter(!is.na(`Food groups lvl4`)) %>%
mutate(`Food groups lvl1` = `Food groups lvl1` %>% gsub("Chemicals","Others",.)) %>%
  mutate(`Food groups lvl2` = `Food groups lvl2` %>% gsub("Salts and sauces","Salts and sauce",. )) %>%
  mutate(`Food groups lvl1` = `Food groups lvl1` %>% gsub("Animal-based","Animal-based",.)) -> data

# transform it to a edge list!
edges_level0_1 <- data %>% select(`Food groups lvl0`, `Food groups lvl1`) %>% unique %>% rename(from=`Food groups lvl0`, to=`Food groups lvl1`)
edges_level1_2 <- data %>%select(`Food groups lvl1`, `Food groups lvl2`) %>% unique %>% rename(from=`Food groups lvl1`, to=`Food groups lvl2`)
edges_level2_3 <- data %>%select(`Food groups lvl2`, `Food groups lvl3`) %>% unique %>% rename(from=`Food groups lvl2`, to=`Food groups lvl3`)
edges_level3_4 <- data %>%select(`Food groups lvl3`, `Food groups lvl4`) %>% unique %>% rename(from=`Food groups lvl3`, to=`Food groups lvl4`)
edge_list=rbind(edges_level0_1,edges_level1_2, edges_level2_3,edges_level3_4)


```


```{r fig.height=10, fig.width=10}
edge_list %>%
  igraph::graph_from_data_frame() %>%
  tidygraph::as_tbl_graph() %>%
  mutate(leaf = node_is_leaf(), root = node_is_root()) %>%
  mutate(root=ifelse(name=="Food",TRUE,FALSE)) %>%
  ggraph('dendrogram', circular = TRUE) + 
  geom_edge_elbow() + 
  coord_fixed() +
  geom_node_point(size=1) +
  geom_node_point(aes(filter = leaf), colour = 'forestgreen', size = 5) +
  geom_node_point(aes(filter = root), colour = 'firebrick', size = 10) +
  geom_node_label(aes(label=name %>% gsub(" ","\n",.)),repel = TRUE, size=3,segment.alpha = 0.5) +
  theme_graph() -> food_tree_plot

save(food_tree_plot, file="food_tree_plot.rda")

food_tree_plot

ggsave("food_tree.pdf",h=10,w=10)


# edge_list %>%
#   igraph::graph_from_data_frame() %>%
#   tidygraph::as_tbl_graph() %>%
#   mutate(leaf = node_is_leaf(), root = node_is_root()) %>%
#   mutate(root=ifelse(name=="Food",TRUE,FALSE)) %>%
# ggraph('partition', circular = TRUE) + 
#     geom_node_arc_bar(aes(fill = depth), size = 0.25) +
#   coord_fixed() +
#   geom_node_point(aes(filter = leaf), colour = 'forestgreen', size = 5) +
#   geom_node_point(aes(filter = root), colour = 'firebrick', size = 10) +
#   geom_node_label(aes(label=name %>% gsub(" ","\n",.)),repel = TRUE) +
#   theme_graph()


```


