---
title: "Hydrolases analysis"
output: html_notebook
---



```{r}

devtools::load_all()

library(IBSMicrobiota)
library(dplyr)
library(ggplot2)

data("hydrolase_hit")
data("cazy_counts")
data("total_reads")
data("MSP_genes_id_corresp")
data("MSP_tax")
data("IBSData")

```



```{r}

hydrolase_hit %>%
  merge(MSP_genes_id_corresp %>% 
          select(msp_name,module_name,gene_name_v2), 
        by.x="subject id", by.y="gene_name_v2") %>% 
  merge(MSP_tax, by.x="msp_name", by.y="MSP_ID")


```


```{r}

hydrolase_hit %>%
  merge(MSP_genes_id_corresp %>% 
          select(msp_name,module_name,gene_name_v2), 
        by.x="subject id", by.y="gene_name_v2") %>% 
  merge(MSP_tax, by.x="msp_name", by.y="MSP_ID") %>%
  select(Organism,species,phylum,family, `New Class`) %>%
  with(., xtabs(~`New Class`+phylum)) %>%
  heatmap()



```



```{r, eval=FALSE, include=FALSE}


hydrolase_hit %>%
  merge(MSP_genes_id_corresp %>% 
          select(msp_name,module_name,gene_name_v2), 
        by.x="subject id", by.y="gene_name_v2") %>% 
  merge(MSP_tax, by.x="msp_name", by.y="MSP_ID") %>%
  merge(counts_rescaled, by.x="subject id", by.y="genes.id") -> hydrolase_count_rescaled


save(hydrolase_count_rescaled, file="hydrolase_count_rescaled.rda")


```




```{r}

load("hydrolase_count_rescaled.rda")

hydrolase_count_rescaled %>%
  group_by(`New Class`) %>%
  summarise_at(vars(contains("M",ignore.case = FALSE)), sum) %>%
  reshape2::melt() %>%
  merge(total_reads %>% as.matrix %>% as.data.frame(), by.x="variable",by.y="row.names") %>%
  mutate(value=value/V1) %>%
  
  reshape2::dcast(variable~`New Class`, value.var="value") %>%
  #mutate_at(vars(contains("M",ignore.case = FALSE)), function(x){x/sum(x)}  ) %>%
  #as.data.frame() %>%
  #tibble::column_to_rownames("New Class") %>%
  tibble::column_to_rownames("variable") %>%
  as.matrix() %>% t %>% na.omit %>% t %>%
  heatmap()


```


```{r}

hydrolase_count_rescaled %>%
  group_by(`New Class`) %>%
  summarise_at(vars(contains("M",ignore.case = FALSE)), sum) %>%
  reshape2::melt() %>%
  merge(total_reads %>% as.matrix %>% as.data.frame(), by.x="variable",by.y="row.names") %>%
  mutate(value=value/V1) %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool"),
  by.y="Patient_ID",
  by.x="variable"
    
  ) %>%
  merge(enterotypes %>% filter(Visit=="V4"), by.x="variable", by.y="Patient_ID") %>%
  
ggplot() + geom_boxplot(aes(y=value+10^-6,x=enterotypes %>% as.character)) + facet_wrap(~`New Class`, scales="free_y") 



hydrolase_count_rescaled %>%
  group_by(`New Class`) %>%
  summarise_at(vars(contains("M",ignore.case = FALSE)), sum) %>%
  mutate_at(vars(contains("M",ignore.case = FALSE)), function(x){x/sum(x)}  ) %>%
  #as.data.frame() %>%
  #tibble::column_to_rownames("New Class") %>%

  reshape2::melt(id.vars="New Class") %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool"),
  by.y="Patient_ID",
  by.x="variable"
    
  ) %>%
  merge(enterotypes %>% filter(Visit=="V4"), by.x="variable", by.y="Patient_ID") %>%
  filter(!is.na(value)) %>%
  filter(!is.na(SSgroup)) %>%
  ggplot() + geom_boxplot(aes(y=value+10^-6,x=SSgroup)) + facet_wrap(~`New Class`, scales="free_y") + scale_y_log10()



hydrolase_count_rescaled %>%
  group_by(`New Class`) %>%
  summarise_at(vars(contains("M",ignore.case = FALSE)), sum) %>%
  mutate_at(vars(contains("M",ignore.case = FALSE)), function(x){x/sum(x)}  ) %>%
  #as.data.frame() %>%
  #tibble::column_to_rownames("New Class") %>%

  reshape2::melt(id.vars="New Class") %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool"),
  by.y="Patient_ID",
  by.x="variable"
    
  ) %>%
  merge(enterotypes %>% filter(Visit=="V4"), by.x="variable", by.y="Patient_ID") %>%
  filter(!is.na(value)) %>%
  filter(!is.na(SSgroup)) %>%
  group_by(`New Class`) %>%
  mutate(IBS.Severity.Score = ifelse(SSgroup=="control",0,IBS.Severity.Score)) %>%
  mutate(SSgroup = as.numeric(SSgroup)) %>%
  #do(with(.,cor.test(data=., .$value , .$IBS.Severity.Score, method="spearman") %>% broom::tidy())) 
  #filter(SSgroup %in% c(1,4)) %>%
  do(with(.,cor.test(data=., .$value , .$SSgroup, method="spearman") %>% broom::tidy())) 





hydrolase_count_rescaled %>%
  group_by(`New Class`) %>%
  summarise_at(vars(contains("M",ignore.case = FALSE)), sum) %>%
  mutate_at(vars(contains("M",ignore.case = FALSE)), function(x){x/sum(x)}  ) %>%
  #as.data.frame() %>%
  #tibble::column_to_rownames("New Class") %>%

  reshape2::melt(id.vars="New Class") %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool"),
  by.y="Patient_ID",
  by.x="variable"
    
  ) %>%
  merge(enterotypes %>% filter(Visit=="V4"), by.x="variable", by.y="Patient_ID") %>%
  filter(!is.na(value)) %>%
  group_by(`New Class`) %>%
  do(with(.,wilcox.test(data=., .$value~ .$CH4>10)%>%broom::tidy()))


```



```{r}

hydrolase_count_rescaled %>% 
  ungroup() %>%
  group_by(`New Class`) %>%
  select(contains("M", ignore.case = FALSE)) %>%
  summarise_all(sum) %>%
  reshape2::melt(id.vars="New Class") %>%
  merge(total_reads %>% as.matrix %>% as.data.frame, by.y="row.names", by.x="variable") %>%
  mutate(value=value/V1) %>%
  reshape2::dcast(`New Class`~variable, value.var = "value") -> hydrogenase_normalized




hydrolase_count_rescaled %>%
  group_by(`New Class`) %>%
  summarise_at(vars(contains("M",ignore.case = FALSE)), sum) %>%
  mutate_at(vars(contains("M",ignore.case = FALSE)), function(x){x/sum(x)}  ) %>%
  as.data.frame() %>%
  tibble::column_to_rownames("New Class") %>%
  t %>%
  na.omit() %>%
  magrittr::add(10^-6) %>%
  log10() -> hydrogenase_norm


  #ade4::dudi.pca(hydrogenase_normalized %>% tibble::column_to_rownames("New Class") %>% t %>% as.data.frame, scannf=F, nf=10) -> hydrogene_pca

ade4::dudi.pca(hydrogenase_norm, scannf=F, nf=10) -> hydrogene_pca

  ade4::s.label(hydrogene_pca$co, yax=3, xax=1)

  
  H = hydrogenase_normalized %>% tibble::column_to_rownames("New Class") %>% t %>% as.data.frame %>% #magrittr::add(10^-6) %>%  magrittr::add(10^-6) %>%
    
  merge(enterotypes %>% filter(Visit=="V4"), by.x="row.names", by.y="Patient_ID") %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool"),
  by.y="Patient_ID",
  by.x="Row.names"
    
  ) 
  
  
  H %>%
     filter(SSgroup %in% c("control","severe")) %>%
     tibble::column_to_rownames("Row.names") %>%
    select(contains("[FeFe")) -> H_select
    
    
  
  
  
  dis1 = ade4::discrimin(ade4::dudi.pca(H_select, scannf=FALSE), fac= H %>%
     filter(SSgroup %in% c("control","severe")) %>%
     tibble::column_to_rownames("Row.names") %>% .$SSgroup %>% as.character %>% as.factor, scan=FALSE)
  
  plot(dis1)
  
  ade4::randtest(dis1)

  
  
  dis1$va %>%
    as.data.frame() %>%
    tibble::rownames_to_column("Hydrogenase") %>%
    ggplot() + geom_bar(aes(x=Hydrogenase, y=CS1), stat="identity") +
    coord_flip() + 
    ylab("LDA scores\n(association with\nsymptoms severity)") + 
    cowplot::theme_cowplot() -> LDA_hydrogenase_plot
  
  
  
  H %>%
    select(contains("[FeFe"), SSgroup) %>%
    na.omit() %>%
    reshape2::melt(id.vars="SSgroup") %>%
    filter(SSgroup %in% c("control","severe")) %>%
    #mutate(value=10^value) %>%
    filter(variable %in% c("[FeFe] Group A3")) %>%
    ggplot() + geom_boxplot(aes(x=SSgroup,y=value)) + facet_wrap(~variable, scales = "free_y") +
    #scale_y_log10() +
    ylab("rel. abundance") +
    xlab("Symptoms severity") +
    cowplot::theme_cowplot() -> FeFe_A3_severity_plot
  
  
  
  
```


```{r}

load("nutriscore_DI.rda")


nutriscore_DI %>%
  merge(.,H, by.x="Patient_ID", by.y="Row.names") %>%
  select(Patient_ID,nutriscore_DI, contains("[FeFe"), contains("[Fe]"), contains("[NiFe")) %>%
  reshape2::melt(id.vars=c("Patient_ID","nutriscore_DI")) %>%
  group_by(variable) %>%
  do(with(.,cor.test(.$nutriscore_DI,.$value, method="spearman") %>% broom::tidy()))


  


```



```{r}

  

hydrogene_pca$li %>%
  merge(enterotypes %>% filter(Visit=="V4"), by.x="row.names", by.y="Patient_ID") %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool"),
  by.y="Patient_ID",
  by.x="Row.names"
    
  ) %>%
  ggplot()+geom_point(aes(x=Axis1, y=Axis3, size=(CH4+1)/(H2+1)))


hydrogene_pca$li %>%
  merge(enterotypes %>% filter(Visit=="V4"), by.x="row.names", by.y="Patient_ID") %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool"),
  by.y="Patient_ID",
  by.x="Row.names"
    
  ) %>%
  ggplot()+geom_boxplot(aes(x=Health, y=Axis3))




hydrogene_pca$li %>%
  merge(enterotypes %>% filter(Visit=="V4"), by.x="row.names", by.y="Patient_ID") %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool"),
  by.y="Patient_ID",
  by.x="Row.names"
    
  ) %>% 
    with(.,cor.test(data=., .$Axis3, .$SSgroup %>% as.numeric, method="spearman"))


hydrogene_pca$li %>%
  merge(enterotypes %>% filter(Visit=="V4"), by.x="row.names", by.y="Patient_ID") %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool"),
  by.y="Patient_ID",
  by.x="Row.names"
    
  ) %>% 
  select(Row.names, contains("Axis"),H2,CH4) %>%
  reshape2::melt(id.vars=c("Row.names","H2","CH4")) %>%
  group_by(variable) %>%
  do(with(.,wilcox.test(data=., .$value~ .$H2>10)%>%broom::tidy()))


  


  
  ade4::s.label(hydrogene_pca$co, yax=3, xax=1)
  
```


Axis 1 = associated with low H2 and High CH4 and with slower transit
Axis 2 = associated with CH4
Axis 3 = associated with severity


```{r}


hydrolase_count_rescaled %>%
  group_by(`New Class`) %>%
  summarise_at(vars(contains("M",ignore.case = FALSE)), sum) %>%
  mutate_at(vars(contains("M",ignore.case = FALSE)), function(x){x/sum(x)}  ) %>%
  as.data.frame() %>%
  reshape2::melt(id.vars=c("New Class")) %>%
merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool") %>% select(Patient_ID,SSgroup),
  by.y="Patient_ID",
  by.x="variable"
    
  )


hydrolase_count_rescaled %>%
  group_by(`New Class`) %>%
  summarise_at(vars(contains("M",ignore.case = FALSE)), sum) %>%
  mutate_at(vars(contains("M",ignore.case = FALSE)), function(x){x/sum(x)}  ) %>%
  as.data.frame() %>%
  filter(`New Class` %in% c("[FeFe] Group A1","[FeFe] Group A3")) %>%
  tibble::column_to_rownames("New Class") %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("Patient_ID") %>%
  mutate(A1_A3 = `[FeFe] Group A1` /  `[FeFe] Group A3`) %>%
  merge(
    IBSData$metadata %>%
  filter(Visit=="V4", Sample_type=="Stool") %>% select(Patient_ID,SSgroup, `IBS.Severity.Score`),
  by="Patient_ID"
    
  ) %>%
  na.omit() %>%
  with(.,pairwise.wilcox.test(g=SSgroup, x=A1_A3, p.adjust.method = "none"))

  





```


```{r}





#cazy_counts = read.csv2(system.file("cazy_counts.csv"), row.names = 1) 



hydrolase_count_rescaled %>% 
  ungroup() %>%
  group_by(`New Class`) %>%
  select(contains("M", ignore.case = FALSE)) %>%
  summarise_all(sum) %>%
  reshape2::melt(id.vars="New Class") %>%
  merge(total_reads %>% as.matrix %>% as.data.frame, by.y="row.names", by.x="variable") %>%
  mutate(value=value/V1) %>%
  reshape2::dcast(`New Class`~variable, value.var = "value") -> hydrogenase_normalized
  



cazy_counts %>% 
  reshape2::melt(id.vars="cazy_family") %>%
  merge(total_reads %>% as.matrix %>% as.data.frame, by.y="row.names", by.x="variable") %>%
  mutate(value=value/V1) %>%
  reshape2::dcast(`cazy_family`~variable, value.var = "value") -> cazy_normalized






```



```{r fig.height=10, fig.width=10}

library(igraph)
library(ggraph)



hydrogenase_normalized %>% 
  #mutate_at(vars(contains("M",ignore.case = FALSE)), function(x){x/sum(x)}  ) %>%
  as.data.frame %>%
  dplyr::rename(cazy_family = `New Class`) %>%
  rbind(cazy_normalized) %>%
  tibble::column_to_rownames("cazy_family") %>%
  t() %>% #na.omit() %>%
  cor(method="spearman") %>%
  reshape2::melt() %>%
  filter(abs(value) > 0.4) %>%
  filter(Var1 %in% hydrogenase_normalized$`New Class` & Var2 %in% cazy_normalized$cazy_family) -> edges

edges %>%
  igraph::graph.data.frame(directed=FALSE) -> g

V(g)$type <- V(g)$name %in% edges[,2] #the second column of edges is TRUE type
E(g)$weight <- as.numeric(edges[,3])

g %>%
  #igraph::add_layout_(igraph::as_bipartite()) %>%
  igraph::plot.igraph()




```


```{r}



#https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4365749/
# and smiths 2017 and ragideau and cantarel 2012

cazy_mucinase_acivity = 
  c("GH33","CBM40","GH29","CBM32",
    "GH95","CBM51","GH98","GH101",
    "GH129","GH20","GH2","GH42",
    "GH84","GH89", "CBM40")

cazy_fiber_activity = 
  c("GH3","GH5","GH8","GH9",
    "GH10","GH13","GH16","GH26",
    "GH28","GH30","GH32","GH39",
    "GH32","GH39","GH43","GH44",
    "GH48","GH51","GH74","GH91",
    "GH115","GH120","GH127","PL1",
    "PL9","PL11")


Plant_Cell_Wall = c("GH1", "GH2", "GH3", "GH4", "GH5", "GH8", "GH9", "GH11", "GH12", "GH15", "GH16", "GH17", "GH26", "GH27", "GH28", "GH36", "GH39", "GH43", "GH44", "GH48", "GH51", "GH53", "GH55", "GH67", "GH74", "GH78", "GH93", "GH94", "GH95", "GH115", "GH117", "GH121", "PL1", "PL2", "PL6", "PL7", "PL9", "PL11", "PL15", "PL22", "CBM9")



Animal = c("GH1", "GH2", "GH3", "GH4", "GH18", "GH19", "GH20", "GH29", "GH33", "GH38", "GH58", "GH79", "GH84", "GH85", "GH88", "GH89", "GH92", "GH95", "GH98", "GH99", "GH101", "GH105", "GH109", "GH110", "GH113", "PL6", "PL8", "PL12", "PL13", "PL21", "GH123")


Mucin = c("GH2", "GH20", "GH27", "GH29", "GH33", "GH35", "GH36", "GH95", "GH89", "GH110", "GH129")

Mucin = c(Mucin,cazy_mucinase_acivity) %>% unique

Peptidoglycan = c("GH23", "GH24", "GH25", "GH73", "GH102", "GH103", "GH104", "GH108")

Starch_Glycogen = c("GH13", "GH15", "GH57", "GH77", "CBM34", "CBM48")

Sucrose_Fructans = c("GH32", "GH68", "GH70", "GH91", "CBM66")

#Fungal = c("GH5", "GH8", "GH16", "GH18", "GH19", "GH20", "GH55", "GH64", "GH71", "GH81")
#Dextran= c("GH66", "GH70", "GH87")

Plant_based = c(cazy_fiber_activity, Plant_Cell_Wall, Starch_Glycogen, Sucrose_Fructans) %>% unique



cazy_substrates = 
rbind(
  
  data.frame(cazy=Plant_based,substrates="01 Plant_based"),
  data.frame(cazy=Animal,substrates="02 Animal or Mucin"),
  data.frame(cazy=Mucin, substrates="02 Animal or Mucin"),
  data.frame(cazy=Peptidoglycan, substrates="03 Peptidoglycan")
  
) %>% unique

cazy_substrates$substrates = as.character(cazy_substrates$substrates)

cazy_substrates %>%
  filter(cazy=="GT71")


```

## create network hydrogenase vs cazy

```{r}

library(igraph)
library(ggraph)

hydrogenase_normalized %>% 
  #mutate_at(vars(contains("M",ignore.case = FALSE)), function(x){x/sum(x)}  ) %>%
  dplyr::rename(cazy_family = `New Class`) %>%
  rbind(cazy_normalized) %>%
  tibble::column_to_rownames("cazy_family") %>%
  t() %>% #na.omit %>%
  cor(method="spearman") %>%
  reshape2::melt() %>%
  filter(abs(value) > 0.4) %>%
  filter(Var1 %in% hydrogenase_normalized$`New Class` & Var2 %in% cazy_normalized$cazy_family) -> edges

set.seed(131082)
edges  %>% 
  mutate(remove=grepl("CE|AA",Var2)) %>%
  filter(remove!=TRUE) %>%
  select(-remove) %>%
  graph_from_data_frame() -> g

V(g)$label = names(V(g)) %>% gsub(" Group "," ", .)

V(g)$Family = V(g)$label %>%  grepl("\\[",.) %>% ifelse(.,"Hydrogenase","CAZy")

g_metadata = 
merge(data.frame(cazy = V(g)$label, `Functional\nfamily` = V(g)$Family), cazy_substrates,  all.x = TRUE ) %>%
  mutate(substrates = ifelse(is.na(substrates)  , "Others"  , as.character(substrates) ))

#V(g) %>% length
#g_metadata$substrates %>% length


V(g)$substrates = g_metadata$substrates


set.seed(131082)
p_network =
  ggraph(g,'igraph', algorithm = 'nicely') +
    #geom_edge_link() +
   geom_edge_link(aes(start_cap = circle(3, 'mm'),
                        end_cap = circle(3, 'mm'))) + 
  geom_node_point(aes(shape=Family, col=substrates), alpha=0.9, size=10) +
  geom_node_text(aes(label=label), size=2) +
  #scale_size_manual(values=2) +  
  scale_color_manual("CAZy\nassociated\nglycans", 
                     values = c("#1b9e77","#d95f02","#7570b3","grey"), 
                     labels = c("Plant based","Meat or Mucins","Peptidoglycan","Others")) +  
  scale_shape_discrete("Functional\nfamily") +
  theme_void() + 
    guides(shape = guide_legend(override.aes = list(size = 3)), color = guide_legend(override.aes = list(size = 3)))
  #theme(legend.position = "none")
p_network 
  ggsave("Network_Figure_Hydrogenase_Cazy.pdf", h = 5, w = 8)
  
#ggraph(g,'igraph', algorithm = 'nicely') %>% unclass

```




```{r, fig.height=6, fig.width=10}


cowplot::plot_grid(p_network, cowplot::plot_grid(LDA_hydrogenase_plot, FeFe_A3_severity_plot, nrow=2, labels = c("B","C")), nrow=1, rel_widths = c(2,1), labels = c("A",NULL))

ggsave("cazy_hydrogenase_network_LDA.pdf", h=6,w=10)


```



```{r}

H %>%
  select(`Row.names`, contains("[FeFe"), SSgroup) %>%
  na.omit() %>%
  reshape2::melt(id.vars=c("SSgroup","Row.names")) %>%
  group_by(`Row.names`,SSgroup) %>%
  filter(SSgroup %in% c("control","severe" )) %>%
  summarize(value=sum(value)) %>%
  #with(.,wilcox.test(.$value~ .$SSgroup ,data=.))
  ggplot() + geom_boxplot(aes(x=SSgroup,y=value))




```


