---
title: "IBS and food metagenome functional analysis"
output: html_notebook
---

```{r}
library(ggplot2)
library(reshape2)
library(magrittr)
library(ade4)
library(dplyr)
devtools::load_all()


```


## load data

- co-inertia analysis and supplemental predicted data
- MSP gut modules data by GoMixer
- infraspecies data

```{r, message=FALSE, warning=FALSE}

load(system.file("data-raw","infraspecies_food_coi_foodsup.rda", package = "IBSFood"))
load(system.file("data-raw","infraspecies_food_coi_spesup.rda",  package = "IBSFood"))
load(system.file("data-raw","infraspecies_food_coi.rda",         package = "IBSFood"))

infraspecies = readr::read_csv2(system.file("infraspecies", "infraspecies_table_full.csv", package="IBSFood"))[,-1]

# MSP_KO_counts=
# read.csv2(system.file("data-raw","MSP_KO_counts.csv",         package = "IBSFood"), row.names = 1)
# 
# KO_counts=
# read.csv2(system.file("data-raw","KO_counts.csv",         package = "IBSFood"), row.names = 1)

# from gomixer
load(system.file("data-raw","modules.rda",         package = "IBSFood"))

load(system.file("data-raw","msp_ko_gut_modules.rda",         package = "IBSFood"))


total_reads = read.csv2(system.file("data-raw","total_reads.csv",         package = "IBSFood"), row.names = 1)


```





## check coinertia
```{r}
# Axis 2 and Axis 4 are linked to gas metabolism, food quality and symptoms severity

microbiota_coinertia = 
rbind(infraspecies_food_coi$lX,infraspecies_food_coi_spesup$lisup) %>%
  select(AxcX1, AxcX2,AxcX4)



```


```{r}

rbind(
  cbind(group="train",infraspecies_food_coi$lX),
  cbind(group="test",infraspecies_food_coi_spesup$lisup))[1:6] %>% 
  merge(.,
        IBSMicrobiota::IBSData$metadata %>%
           filter(Visit=="V4",Sample_type=="Stool"), 
        by.x="row.names", 
        by.y="Patient_ID") %>%
  mutate(H2_CH4 = log2((H2+1)/(CH4+1))) %>%
  #filter((H2<10&CH4>10)|(H2>10&CH4<10)) %>% 
  ggplot() + geom_point(aes(x=H2_CH4, y=AxcX2, col=H2>10))

rbind(
  cbind(group="train",infraspecies_food_coi$lX),
  cbind(group="test",infraspecies_food_coi_spesup$lisup))[1:6] %>% 
  merge(.,
        IBSMicrobiota::IBSData$metadata %>%
           filter(Visit=="V4",Sample_type=="Stool"), 
        by.x="row.names", 
        by.y="Patient_ID") %>%
  mutate(H2_CH4 = log2((H2+1)/(CH4+1))) %>%
  #filter((H2<10&CH4>10)|(H2>10&CH4<10)) %>% 
  ggplot() + geom_point(aes(x=H2_CH4, y=AxcX4, col=H2>10))



rbind(
  cbind(group="train",infraspecies_food_coi$lX),
  cbind(group="test",infraspecies_food_coi_spesup$lisup))[1:6] %>% 
  merge(.,
        IBSMicrobiota::IBSData$metadata %>%
           filter(Visit=="V4",Sample_type=="Stool"), 
        by.x="row.names", 
        by.y="Patient_ID") %>%
  mutate(H2_CH4 = log2((H2+1)/(CH4+1))) %>%
  with(.,cor.test(.$H2_CH4,.$AxcX2, method="spearman"))

rbind(
  cbind(group="train",infraspecies_food_coi$lX),
  cbind(group="test",infraspecies_food_coi_spesup$lisup))[1:6] %>% 
  merge(.,
        IBSMicrobiota::IBSData$metadata %>%
           filter(Visit=="V4",Sample_type=="Stool"), 
        by.x="row.names", 
        by.y="Patient_ID") %>%
  mutate(H2_CH4 = log2((H2+1)/(CH4+1))) %>%
  with(.,cor.test(.$H2_CH4,.$AxcX4, method="spearman"))


rbind(
  cbind(group="train",infraspecies_food_coi$lX),
  cbind(group="test",infraspecies_food_coi_spesup$lisup))[1:6] %>% 
  merge(.,
        IBSMicrobiota::IBSData$metadata %>%
           filter(Visit=="V4",Sample_type=="Stool"), 
        by.x="row.names", 
        by.y="Patient_ID") %>%
  mutate(H2_CH4 = log2((H2+1)/(CH4+1))) %>%
  #filter((H2<10&CH4>10)|(H2>10&CH4<10)) %>% 
  ggplot() + geom_point(aes(x=H2_CH4, y=AxcX4-AxcX2, col=H2>10))





```




## gut modules correlations


### correlation to coinertia axis
```{r, message=FALSE, warning=FALSE}

modules_global = cbind(mods@annotation, sweep(mods@abundance, 2, total_reads[mods2@abundance %>% colnames(),], "/"))

modules_per_MSP = cbind(mods2@annotation, sweep(mods2@abundance, 2, total_reads[mods2@abundance %>% colnames(),], "/"))

modules_global %>%
  melt(id.vars="Module") %>%
  merge(.,microbiota_coinertia, by.x="variable",by.y="row.names") %>%
  group_by(Module) %>%
  do(
    ax1_cor=with(., cor.test(.$value,.$AxcX1, method="spearman") %>% broom::tidy()),  
    ax2_cor=with(., cor.test(.$value,.$AxcX2, method="spearman") %>% broom::tidy()),  
    ax4_cor=with(., cor.test(.$value,.$AxcX4, method="spearman") %>% broom::tidy())
    ) %>%
  tidyr::unnest(ax1_cor, ax2_cor,ax4_cor, .drop = TRUE) %>%
  dplyr::rename(ax1_cor=estimate, ax1_p = `p.value`, ax2_cor=estimate1, ax2_p = `p.value1`, ax4_cor = estimate2, ax4_p = `p.value2`) %>%
  select(Module, ax1_cor, ax1_p, ax2_cor, ax2_p, ax4_cor, ax4_p) %>%
  filter(ax1_p < 0.05 | ax2_p < 0.05 | ax4_p < 0.05) -> modules_cor

module_global_name = 
apply(modules_cor, 1, function(x)getNames(db, x[1]))

#%>%
 # group_by(Module) %>%
  #do(annot=with(.,getNames(db, .$Module ))) %>%
  #tidyr::unnest(annot)



modules_per_MSP %>%
  melt(id.vars=c("Taxon","Module")) %>%
  merge(.,microbiota_coinertia, by.x="variable",by.y="row.names") %>%
  group_by(Taxon,Module) %>%
  do(
    ax1_cor=with(., cor.test(.$value,.$AxcX1, method="spearman") %>% broom::tidy()),  
    ax2_cor=with(., cor.test(.$value,.$AxcX2, method="spearman") %>% broom::tidy()),  
    ax4_cor=with(., cor.test(.$value,.$AxcX4, method="spearman") %>% broom::tidy())
    ) %>%
  tidyr::unnest(ax1_cor, ax2_cor,ax4_cor, .drop = TRUE) %>%
  dplyr::rename(ax1_cor=estimate, ax1_p = `p.value`, ax2_cor=estimate1, ax2_p = `p.value1`, ax4_cor = estimate2, ax4_p = `p.value2`) %>%
  select(Taxon,Module, ax1_cor, ax1_p, ax2_cor, ax2_p, ax4_cor, ax4_p) %>%
  filter(ax1_p < 0.05 | ax2_p < 0.05 | ax4_p < 0.05) -> MSP_modules_cor

module_name = 
apply(MSP_modules_cor, 1, function(x)getNames(db, x[2]))

  
save(MSP_modules_cor, file="MSP_modules_cor.rda")

```




```{r}

modules_cor %>%
  cbind(module_global_name) %>%
  filter( abs(ax2_cor) > 0.2) %>%
  arrange(desc(ax2_cor)) %>%
  select(module_global_name,ax2_cor)

modules_cor %>%
  cbind(module_global_name) %>%
  filter( abs(ax4_cor) > 0.2) %>%
  arrange(desc(ax4_cor)) %>%
  select(module_global_name,ax4_cor)




```


```{r}

module_name = 
apply(MSP_modules_cor, 1, function(x)getNames(db, x[2]))



MSP_modules_cor %>%
  cbind(module_name) %>%
  merge(infraspecies %>% select(msp_name,species, genus) %>% unique, by.x="Taxon", by.y="msp_name") %>%
  #filter( abs(ax2_cor) > 0.4 | abs(ax4_cor) > 0.4 ) %>%
  #arrange(desc(ax2_cor))
  filter( abs(ax1_cor) > 0.4) %>%
  arrange(desc(ax1_cor)) %>%
   select(species,ax1_cor,module_name, Module)

MSP_modules_cor %>%
  cbind(module_name) %>%
  merge(infraspecies %>% select(msp_name,species, genus) %>% unique, by.x="Taxon", by.y="msp_name") %>%
  filter( abs(ax2_cor) > 0.4 ) %>%
  arrange(desc(ax2_cor)) %>%
  select(species,ax2_cor,module_name, Module)


MSP_modules_cor %>%
  cbind(module_name) %>%
  merge(infraspecies %>% select(msp_name,species, genus) %>% unique, by.x="Taxon", by.y="msp_name") %>%
  filter( abs(ax4_cor) > 0.4 ) %>%
  arrange(desc(ax4_cor)) %>%
  select(species,ax4_cor,module_name, Module)



```



```{r}

MPS_modules_cor %>%
  group_by(Taxon , Module) %>%
  do(annot=with(.,getNames(db, .$Module ))) %>%
  tidyr::unnest(annot)

```



### check H2/CH4 ratio

```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}

modules_per_MSP %>%
  melt(id.vars=c("Taxon","Module")) %>%
  merge(.,IBSData$metadata %>% 
          filter(Visit=="V4", Sample_type=="Stool"), by.y="Patient_ID", by.x="variable") %>%
  group_by(Taxon,Module) %>%
  do(H2_CH4_cor=with(., cor.test(.$value,log2((.$H2+1)/(.$CH4+1)), method="spearman") %>% broom::tidy())) %>%
  tidyr::unnest(H2_CH4_cor, .drop=TRUE) %>%
  filter(p.value<0.05) -> modules_H2_CH4_MSP_cor


module_H2_CH4_MSP_cor_name = 
apply(modules_H2_CH4_MSP_cor, 1, function(x)getNames(db, x[2]))

modules_H2_CH4_MSP_cor %>%
  cbind(module_H2_CH4_MSP_cor_name) %>%
  merge(infraspecies %>% select(msp_name,species, genus) %>% unique, by.x="Taxon", by.y="msp_name") %>%
  filter(abs(estimate) > 0.3) %>%
  select(estimate,module_H2_CH4_MSP_cor_name, species) %>%
  arrange(estimate)


modules_per_MSP %>%
  melt(id.vars=c("Taxon","Module")) %>%
  merge(.,IBSData$metadata %>% 
          filter(Visit=="V4", Sample_type=="Stool"), by.y="Patient_ID", by.x="variable") %>%
  group_by(Taxon,Module) %>%
  do(H2_cor=with(., cor.test(.$value,.$H2, method="spearman") %>% broom::tidy())) %>%
  tidyr::unnest(H2_cor, .drop=TRUE) %>%
  filter(p.value<0.05) -> modules_H2_MSP_cor


module_H2_MSP_cor_name = 
apply(modules_H2_MSP_cor, 1, function(x)getNames(db, x[2]))

modules_H2_MSP_cor %>%
  cbind(module_H2_MSP_cor_name) %>%
  merge(infraspecies %>% select(msp_name,species, genus) %>% unique, by.x="Taxon", by.y="msp_name") %>%
  filter(abs(estimate) > 0.3) %>%
  select(estimate,module_H2_MSP_cor_name, species) %>%
  arrange(estimate)




modules_global %>%
  melt(id.vars=c("Module")) %>%
  merge(.,IBSData$metadata %>% 
          filter(Visit=="V4", Sample_type=="Stool"), by.y="Patient_ID", by.x="variable") %>%
  group_by(Module) %>%
  do(  H2_CH4_cor=with(., cor.test(.$value,log2((.$H2+1)/(.$CH4+1)), method="spearman") %>% broom::tidy())) %>%
  tidyr::unnest(H2_CH4_cor, .drop=TRUE) %>%
  filter(p.value<0.05) -> modules_H2_CH4_cor

module_H2_CH4_cor_name = 
apply(modules_H2_CH4_cor, 1, function(x)getNames(db, x[1]))


modules_H2_CH4_cor %>%
  cbind(module_H2_CH4_cor_name) %>%
  select(estimate,module_H2_CH4_cor_name) %>%
  arrange(estimate)



modules_global %>%
  melt(id.vars=c("Module")) %>%
  merge(.,IBSData$metadata %>% 
          filter(Visit=="V4", Sample_type=="Stool"), by.y="Patient_ID", by.x="variable") %>%
  group_by(Module) %>%
  do(  H2_cor=with(., cor.test(.$value,.$H2, method="spearman") %>% broom::tidy())) %>%
  tidyr::unnest(H2_cor, .drop=TRUE) %>%
  filter(p.value<0.05) -> modules_H2_cor

module_H2_cor_name = 
apply(modules_H2_cor, 1, function(x)getNames(db, x[1]))


modules_H2_cor %>%
  cbind(module_H2_cor_name) %>%
  select(estimate,module_H2_cor_name) %>%
  arrange(estimate)




```


## check infraspecies modules



```{r, fig.height=5, fig.width=10}


msp_target = "msp_0071"

infraspecies_select=
infraspecies %>% 
  filter(msp_name==msp_target) %>%
  select(contains("M", ignore.case = FALSE), msp_name_partition,msp_name,species) %>%
  melt(id.vars=c("msp_name_partition","msp_name","species")) %>%
  group_by(variable) %>%
  top_n(1)



modules_per_MSP %>%
  filter(Taxon==msp_target) %>%
  melt(id.vars=c("Taxon","Module")) %>%
  merge(infraspecies_select, by="variable") %>%
  ungroup %>%
  ggplot() + geom_point(aes(x=value.x,y=value.y,col=msp_name_partition))
  

modules_per_MSP %>%
  filter(Taxon==msp_target) %>%
  melt(id.vars=c("Taxon","Module")) %>%
  merge(infraspecies_select, by="variable") %>%
  ungroup %>% 
  group_by(msp_name_partition) %>%
  mutate(value= log10(value.x+10^-6) %>% scale) %>%
  filter(!(msp_name_partition %in% grep("unassigned",msp_name_partition, value=TRUE )) ) %>%
  #filter(Module %in% c("MF0001","MF0038")) %>%
  ggplot() + 
  geom_tile(aes(y=Module,x=variable,fill=value)) + 
  facet_wrap(~msp_name_partition, scales = "free_x") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0, size=2), axis.text.y  = element_text(size=4))



modules_per_MSP %>%
  filter(Taxon==msp_target) %>%
  melt(id.vars=c("Taxon","Module")) %>%
  merge(infraspecies_select, by="variable") %>%
  ungroup %>% 
  group_by(msp_name_partition) %>%
  mutate(value= log10(value.x+10^-6) %>% scale) %>%
  filter(!(msp_name_partition %in% grep("unassigned",msp_name_partition, value=TRUE )) ) %>%
  ggplot() + geom_boxplot(aes(y=value ,x=Module, fill=msp_name_partition)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0, size=10))




```




```{r}

modules_per_MSP = cbind(mods2@annotation, sweep(mods2@abundance, 2, total_reads[mods2@abundance %>% colnames(),], "/"))



modules_per_MSP %>%
  melt(id.vars=c("Taxon","Module")) %>%
  group_by(variable) %>%
  summarize(s = sum(value)) %>%
  ggplot() + geom_histogram(aes(x=s %>% as.character %>% as.numeric()))


mods2@abundance %>%
  melt() %>%
  group_by(variable) %>%
  summarize(s = sum(value) %>% round(1)) %>%
  merge(total_reads, by.x="variable", by.y="row.names") %>%
  mutate(p=s/V1) %>%
  arrange(desc(p))
  
  
  ggplot() + geom_histogram(aes(x=s %>% as.character %>% as.numeric()))


```


