---
title: "IBS food exploration"
output:
  html_notebook:
    author: "Julien Tap"
    code_folding: hide
    highlight: tango
    mathjax: null
    theme: cerulean
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
date: '`r Sys.Date()`'
---


## Introduction

```{r, message=FALSE, warning=FALSE}
library(tidyr)
library(dplyr)
library(magrittr)
library(reshape2)
library(circlepackeR)
library(vegan)
library(ggplot2)
library(DirichletMultinomial)

library(IBSMicrobiota)
library(ade4)
library(phyloseq)
data("IBSData")

```


## load dataset

```{r}
devtools::load_all()
data("food_data")
data("food_group_levels")
data("food_swe")
data("mgs_clades_prop")

beta = system.file("beta/beta_mgs.csv", package = "IBSFood") %>% read.csv2(row.names = 1)





```

## food tree

```{r}

food_group_levels %>%
  merge(food_swe %>% select(Livsmedelsnummer, `Energi (kcal)(kcal)`), by="Livsmedelsnummer" ) %>%
    mutate(pathString=paste(`Food groups lvl0`,`Food groups lvl1`,`Food groups lvl2`,`Food groups lvl3`, `Food groups lvl4`, Foodstuffs, sep="//")) %>%
  filter(used == "yes") %>%
  data.tree::as.Node(pathDelimiter = "//") -> food_tree

food_html = circlepackeR::circlepackeR(food_tree, size="Energi (kcal)(kcal)")

food_html

```




```{r, fig.height=10, fig.width=7}


food_data %>% 
  mutate(Meal = ifelse(Meal == "S-1", "Snack", Meal)) %>%
  mutate(Meal = ifelse(Meal == "S-2", "Snack", Meal)) %>%
  mutate(Meal = ifelse(Meal == "S-3", "Snack", Meal)) %>%
  mutate(Meal = ifelse(Meal == "S-4", "Snack", Meal)) %>%
  mutate(Meal = ifelse(Meal == "S-5", "Snack", Meal)) %>%
  mutate(Meal = ifelse(Meal == "S-6", "Snack", Meal)) %>%
  merge(food_group_levels, by.x="Code",by.y="Livsmedelsnummer", all = FALSE) %>%
  select(-Foodstuffs.y) %>%
  dplyr::rename(Foodstuffs = Foodstuffs.x) %>%
  group_by(Identity, Meal, `Food groups lvl1`, `Food groups lvl2`, `Food groups lvl3`,`Food groups lvl4`) %>%
  summarise(Gram = sum(Gram)) %>%
  filter(`Food groups lvl1` %in% c("Dairy")) %>%
  #ggplot() + geom_tile(aes(x=paste(`Food groups lvl4`,Meal,sep="_"), y=Identity, fill=log10(Gram+1)))
  dcast(Identity ~ `Food groups lvl4` + Meal, value.var = "Gram",fill = 0 ) %>%
  tibble::column_to_rownames("Identity") -> tt


  map2color<-function(x,pal,limits=NULL){
    if(is.null(limits)) limits=range(x)
    pal[findInterval(x,seq(limits[1],limits[2],length.out=length(pal)+1), all.inside=TRUE)]
}


  heatmap(as.matrix(tt), RowSideColors = map2color(tt %>% apply(.,1,function(x) length(which(x>0))), heat.colors(64)  ))
 
  


  
  
```



```{r, eval=FALSE, include=FALSE}

food_fit = mclapply(1:7, dmn, count=as.matrix(round(tt)), verbose=TRUE)


lplc <- sapply(food_fit, laplace); plot(lplc)


cl =mixture(food_fit[[3]], assign = TRUE)

heatmapdmn(food_fit[[1]], food_fit[[3]], count=as.matrix(round(tt)))


cbind(cl, div=tt %>% select(-contains(c("29_1|25_"))) %>% apply(.,1,function(x) length(which(x>0)))) %>% as_tibble() %>% ggplot() + geom_boxplot(aes(x=cl %>% as.character,y=div))


```



## create phyloseq object
```{r}

food_data %>%
  merge(food_group_levels, by.x="Code",by.y="Livsmedelsnummer", all = FALSE) %>%
  select(-Foodstuffs.y) %>%
  dplyr::rename(Foodstuffs = Foodstuffs.x) %>%
  group_by(Identity, `Food groups lvl1`, `Food groups lvl2`, `Food groups lvl3`,`Food groups lvl4`) %>%
  summarise(Gram = sum(Gram)) %>%
  na.omit() %>%
  dcast(Identity ~ `Food groups lvl4`, value.var = "Gram",fill = 0 ) %>%
    tibble::column_to_rownames("Identity") %>%
  t() %>%
  #as_tibble %>%
  round() -> food_otu

#url = system.file("biom", "food.biom", package="IBSFood")
tre = system.file("biom", "food.tree", package="IBSFood")

#physeq = phyloseq::import_biom(url, treefilename = tre)
#phyloseq::import_biom("../inst/biom/food.biom", treefilename = tre) # this does not work

#better to do it manually
TREE=ape::read.tree(file=tre)

TREE$edge.length = rep(1, dim(TREE$edge)[1]) #important to add edge length to compute unifrac distance

TAX = tax_table(food_group_levels %>%
              select(`Food groups lvl1`, `Food groups lvl2`, `Food groups lvl3`,`Food groups lvl4`) %>%
              unique %>%
              na.omit() %>%
              filter(`Food groups lvl4` %in% rownames(food_otu)) %>% tibble::column_to_rownames("Food groups lvl4")%>% as.matrix)


OTU = otu_table(food_otu, taxa_are_rows = TRUE)
physeq=phyloseq::phyloseq(OTU,TAX,TREE)


phy_tree(physeq) <- ape::root(phy=phy_tree(physeq), outgroup="28_3", resolve.root=TRUE, interactive=FALSE)


#otu_wunifrac = phyloseq::distance(physeq, method="wunifrac")
food_unifrac = phyloseq::distance(physeq, method="unifrac")

#food_wunifrac = phyloseq::distance(physeq, method="wunifrac")

```

```{r}


unifrac_pco  = ade4::dudi.pco(food_unifrac %>% ade4::quasieuclid(), scannf=F, nf=3)
#wunifrac_pco = ade4::dudi.pco(food_wunifrac %>% ade4::quasieuclid(), scannf=F, nf=3)


#ade4::scatter(unifrac_pco)
#ade4::scatter(wunifrac_pco)


#unifrac_pco$li





IBSData$otu %>% select(IBSData$metadata %>%
  filter(Visit == "V4", Sample_type == "Stool") %>%
  filter(Patient_ID %in% colnames(OTU)) %>% pull(Sample_ID)
) %>% as.matrix %>% prop.table(2) %>%
  melt() %>% merge(IBSData$tax,by.x="Var1", by.y="row.names") %>%
  group_by(Var2, domain, phylum, class, order, family, genus ) %>%
  summarise(value=mean(value)) %>%
  dcast(Var2~domain+phylum+class+order+family+genus, value.var="value") %>%
  mutate(Var2 = gsub("V4","",Var2)) %>%
  mutate(Var2 = gsub("bis","",Var2)) %>%
  tibble::column_to_rownames("Var2") %>%
  t() -> genus

microbial_otu_jsd = BiotypeR::dist.JSD(genus)


microbial_otu_pco = dudi.pco(microbial_otu_jsd, scannf=F, nf=3)


food_unifrac %>% as.matrix %>% .[colnames(genus),colnames(genus)] %>% as.dist -> food_unifrac_select


unifrac_pco  = dudi.pco(food_unifrac_select %>% ade4::quasieuclid(), scannf=F, nf=3)
mic_food_coi = coinertia(microbial_otu_pco, unifrac_pco, scannf=F, nf=3)

#randtest(mic_food_coi)

#microbial_otu_pco

#randtest(mic_food_coi)

plot(procuste(unifrac_pco$tab, microbial_otu_pco$tab))
procuste.randtest(df2 = microbial_otu_pco$tab,df1 = unifrac_pco$tab,nrepet=100)


```



```{r}

  cor(procuste(unifrac_pco$tab, microbial_otu_pco$tab)$scorX[,1:2],
     t(OTU)[colnames(genus),],
     method="spearman"
       ) %>% t %>% as.data.frame %>% tibble::rownames_to_column() %>% arrange(desc(abs(ax1))) %>%
 na.omit() %>% 
   filter(abs(ax1) > 0.3 | abs(ax2) > 0.3) %>%
   #separate(col=rowname, sep="_", into=c("domain","phylum","order","class","family","genus")) %>%
     ggplot() + geom_point(aes(x=ax1, y=ax2)) + ggrepel::geom_text_repel(aes(x=ax1, y=ax2, label=rowname))



 cor(procuste(unifrac_pco$tab, microbial_otu_pco$tab)$scorY[,1:2],
     t(genus),
     method="spearman"
       ) %>% t %>% as.data.frame %>% tibble::rownames_to_column() %>% arrange(desc(abs(ax1))) %>% 
   na.omit() %>% 
   filter(abs(ax1) > 0.3 | abs(ax2) > 0.3) %>%
   separate(col=rowname, sep="_", into=c("domain","phylum","order","class","family","genus")) %>%
     ggplot() + geom_point(aes(x=ax1, y=ax2)) + ggrepel::geom_text_repel(aes(x=ax1, y=ax2, label=genus))
 
 
 food_group_levels %>% 
   select(contains(" lvl")) %>% unique() %>% 
   merge(.,OTU, by.y="row.names", by.x="Food groups lvl4", all.y = TRUE) %>%
   melt(id.vars=c("Food groups lvl0","Food groups lvl1","Food groups lvl2","Food groups lvl3","Food groups lvl4")) %>%
   group_by(`Food groups lvl3`, variable) %>%
   summarise(value=sum(value)) %>%
   dcast(`Food groups lvl3` ~ variable) %>%
   as.data.frame %>%
   tibble::column_to_rownames("Food groups lvl3") -> OTU_lvl3
 
 
 
 food_group_levels %>% 
   select(contains(" lvl")) %>% unique() %>% 
   merge(.,OTU, by.y="row.names", by.x="Food groups lvl4", all.y = TRUE) %>%
   melt(id.vars=c("Food groups lvl0","Food groups lvl1","Food groups lvl2","Food groups lvl3","Food groups lvl4")) %>%
   group_by(`Food groups lvl2`, variable) %>%
   summarise(value=sum(value)) %>%
   dcast(`Food groups lvl2` ~ variable) %>%
   as.data.frame %>%
   tibble::column_to_rownames("Food groups lvl2") -> OTU_lvl2
 
 
 
 
 food_group_levels %>% 
   select(contains(" lvl")) %>% unique() %>% 
   merge(.,OTU, by.y="row.names", by.x="Food groups lvl4", all.y = TRUE) %>%
   melt(id.vars=c("Food groups lvl0","Food groups lvl1","Food groups lvl2","Food groups lvl3","Food groups lvl4")) %>%
   group_by(`Food groups lvl1`, variable) %>%
   summarise(value=sum(value)) %>%
   dcast(`Food groups lvl1` ~ variable) %>%
   as.data.frame %>%
   tibble::column_to_rownames("Food groups lvl1") -> OTU_lvl1
 
 
 
 cor(procuste(unifrac_pco$tab, microbial_otu_pco$tab)$scorX[,1:2],
     cbind(
        t(OTU)[colnames(genus),], 
        t(OTU_lvl3)[colnames(genus),], 
        t(OTU_lvl2)[colnames(genus),], 
        t(OTU_lvl1)[colnames(genus),]
        ),
     method="spearman"
       ) %>% t %>% as.data.frame %>% tibble::rownames_to_column() %>% arrange(desc(abs(ax1))) %>%
 na.omit() %>% 
   filter(abs(ax1) > 0.4 | abs(ax2) > 0.4) -> a
 
 
 cor(procuste(unifrac_pco$tab, microbial_otu_pco$tab)$scorY[,1:2],
     t(genus),
     method="spearman"
       ) %>% t %>% as.data.frame %>% tibble::rownames_to_column() %>% arrange(desc(abs(ax1))) %>% 
   na.omit() %>% 
   filter(abs(ax1) > 0.4 | abs(ax2) > 0.4) %>%
   separate(col=rowname, sep="_", into=c("domain","phylum","order","class","family","genus")) %>%
     ggplot() + 
   geom_point(aes(x=ax1, y=ax2)) + ggrepel::geom_text_repel(aes(x=ax1, y=ax2, label=genus)) + 
   geom_point(data=a, aes(x=ax1, y=ax2)) +  ggrepel::geom_text_repel(data=a, aes(x=ax1, y=ax2, label=rowname))
 
 

```


```{r, eval=FALSE, include=FALSE}


merge(OTU, genus)

colnames(OTU)
colnames(genus)


merge(t(genus), t(OTU), by="row.names") %>% 
  tibble::column_to_rownames("Row.names") %>%
  cor(method="spearman") -> b
  
idx = apply(b,1,function(x) ifelse(any(abs(x) > 0.30 & abs(x) < 1), TRUE, 0) ) %>% 
  as.vector() %>% is.na

edgebundleR::edgebundle(b[!idx,!idx],cutoff=0.30,tension=0.8,nodesize = 14)




```




## check correlation between CAG and 16S data

```{r}


cag = system.file("CAG", "IBS_Big_CAG_summary.csv", package="IBSFood") %>% read.csv2(row.names=1)



cag %>%
  t %>%
  merge(t(genus), by="row.names")
  

m16S_jsd = genus[,intersect(colnames(genus), colnames(cag))] %>% as.data.frame %>% BiotypeR::dist.JSD()


cag_jsd = cag[,intersect(colnames(genus), colnames(cag))] %>% as.data.frame %>% BiotypeR::dist.JSD()



coinertia(dudi.pco(m16S_jsd, scannf=F, nf=3),
  dudi.pco(cag_jsd, scannf=F, nf=3),
  scannf=F, nf=3) %>% plot


coinertia(dudi.pca(genus[,intersect(colnames(genus), colnames(cag))] %>% t %>% as.data.frame,
scannf=F, nf=3),

dudi.pca(cag[,intersect(colnames(genus), colnames(cag))] %>% t %>% as.data.frame, 
scannf=F, nf=3),
  scannf=F, nf=3) %>% plot()



cor(
  
      genus[,intersect(colnames(genus), colnames(cag))] %>% t %>% as.data.frame,
      cag[,intersect(colnames(genus), colnames(cag))] %>% t %>% as.data.frame,
      method="spearman"
      
      
      ) %>% 
  melt %>%
  filter(value > 0.3) %>%
  filter(Var2 == "GU:37") %>%
  arrange(desc(value))
  




```

coinertia analysis showed good correspondance between 16S and CAG analysis.



## compare food OTU with mgs clades


```{r}

data(mgs_clades_prop)


#mgs_clades_prop[-1] %>% t %>% as.data.frame() %>% tibble::rownames_to_column() %>% tidyr::separate("rowname",into=c("gu","cl"), sep="_") %>% select(gu,cl) %>% filter(cl=="cl2") %>% dim

#merge metadata, MGS and food data
mgs_metadata = 
  IBSData$metadata %>%
  filter(Visit == "V4" & Sample_type == "Stool") %>%
  select(Patient_ID, Methanogens_qPCR, Health, SSgroup, transit.days, BMI, H2, CH4, IBS.Severity.Score, HAD.ANXIETY, HAD.DEPRES, BSF.Mean_Stoolform_total, BSF.Mean_Frequenc_StoolPerDay) %>%
  dplyr::rename(anxiety = HAD.ANXIETY, depress = HAD.DEPRES) %>%
  merge(.,mgs_clades_prop, all.y=TRUE, by.y="samples_id", by.x="Patient_ID") 




food_unifrac_select=
food_unifrac %>%
  as.matrix %>%
  melt %>%
  filter(Var1 %in% mgs_metadata$Patient_ID, Var2 %in% mgs_metadata$Patient_ID) %>%
  dcast(Var1~Var2) %>%
  tibble::column_to_rownames("Var1") %>%
  as.dist

unifrac_select_pco  = ade4::dudi.pco(food_unifrac_select  %>% ade4::quasieuclid(), scannf=F, nf=3)

mgs_metadata_food = 
mgs_metadata %>%
  merge(.,unifrac_select_pco$tab, by.y="row.names", by.x="Patient_ID")
  
mgs_clades_pco = 
dudi.pco(
mgs_metadata_food %>% 
  select(Patient_ID,contains("GU")) %>%
  tibble::column_to_rownames("Patient_ID") %>% 
  t %>%
  BiotypeR::dist.JSD(),
scannf=F, nf=3)


```





### Procuste analysis
 
```{r}





plot(procuste(mgs_metadata_food %>% select(Patient_ID,contains("A", ignore.case = FALSE)) %>% tibble::column_to_rownames("Patient_ID"), mgs_clades_pco$tab) )

procuste.randtest(df2 = mgs_clades_pco$tab,df1 = mgs_metadata_food %>% select(Patient_ID,contains("A", ignore.case = FALSE)) %>%
  tibble::column_to_rownames("Patient_ID"),nrepet=100)


### corr with food level

cor(procuste(
    mgs_metadata_food %>% select(Patient_ID,contains("A", ignore.case = FALSE)) %>%
  tibble::column_to_rownames("Patient_ID"), 
    mgs_clades_pco$tab)$scorX[,1:4],
     cbind(
       t(OTU)[rownames(mgs_clades_pco$tab),],
       t(OTU_lvl3)[rownames(mgs_clades_pco$tab),],
       t(OTU_lvl2)[rownames(mgs_clades_pco$tab),],
       t(OTU_lvl1)[rownames(mgs_clades_pco$tab),]
           
       ),
    
     
     
      method="pearson"
       ) %>% t %>% as.data.frame %>% tibble::rownames_to_column() %>% arrange(desc(abs(ax1))) %>%
 na.omit() %>% 
   filter(abs(ax1) > 0.3 | abs(ax2) > 0.3 | abs(ax3) > 0.3 | abs(ax4) > 0.3 ) %>%
  data.frame(.,item="food")-> a



#### corr with mgs clade

cor(procuste(
    mgs_metadata_food %>% select(Patient_ID,contains("A", ignore.case = FALSE)) %>%
  tibble::column_to_rownames("Patient_ID"), 
    mgs_clades_pco$tab)$scorY[,1:4],
  
  
  mgs_clades_prop %>% 
    tibble::rownames_to_column() %>%
    tibble::column_to_rownames("samples_id") %>%
    select(-rowname) %>%
    as.matrix %>%
    .[rownames(mgs_clades_pco$tab),], 
  
  
  method="pearson") %>% 
  t %>% as.data.frame %>% tibble::rownames_to_column() %>% 
  arrange(desc(abs(ax1))) %>%
 na.omit() %>% 
  filter(abs(ax1) > 0.3 | abs(ax2) > 0.3 | abs(ax3) > 0.3 | abs(ax4) > 0.3 ) %>%
  data.frame(.,item="mgs")-> b


rbind(a,b) %>%
  filter(abs(ax1) > 0.3| abs(ax2) > 0.3  ) %>%
  ggplot() + geom_point(aes(x=ax1, y=ax2, col=item)) + ggrepel::geom_text_repel(aes(x=ax1, y=ax2, label=rowname), size = 2)



rbind(a,b) %>%
  filter(abs(ax1) > 0.3| abs(ax3) > 0.3  ) %>%
  ggplot() + geom_point(aes(x=ax1, y=ax3, col=item)) + ggrepel::geom_text_repel(aes(x=ax1, y=ax3, label=rowname), size = 2)

#beta


rbind(a,b) %>%
  mutate(rowname = rowname %>% gsub("\\.",":", .)) %>%
  merge(., beta, by.x="rowname", by.y = "mgs_clades_names", all.x=TRUE) %>%
  ggplot() + geom_boxplot(aes(x=ax1 %>% cut(2), y=m))
  
  
rbind(a,b) %>%
  mutate(rowname = rowname %>% gsub("\\.",":", .)) %>%
  merge(., beta, by.x="rowname", by.y = "mgs_clades_names", all.x=TRUE) %>%
  wilcox.test(m ~ ax1 > 0, data = .)



```


### link with metadata
```{r, message=FALSE, warning=FALSE}



procuste(
  mgs_metadata_food %>% 
    select(Patient_ID,contains("A", ignore.case = FALSE)) %>%
    tibble::column_to_rownames("Patient_ID"), 
    mgs_clades_pco$tab, 
  nf=10
)$scorY %>%
  merge(mgs_metadata_food[1:12],.,by.x="Patient_ID", by.y="row.names") %>%
  melt(id.vars=c(paste0("ax",1:10),"Patient_ID","Health","SSgroup")) %>%
  melt(id.vars=c("Patient_ID","Health","SSgroup","variable","value"), variable.name = "axis", value.name = "coord") %>%       
  group_by(variable,axis) %>%
  na.omit %>% do(broom::tidy(cor.test(.$value, .$coord, method="spearman"))) %>%
  arrange(p.value)


# 
# 
# procuste(mgs_metadata_food %>% select(Patient_ID,contains("A", ignore.case = FALSE)) %>%
#   tibble::column_to_rownames("Patient_ID"), 
#     mgs_clades_pco$tab)$scorY %>%
#   merge(mgs_metadata_food[1:12],.,by.x="Patient_ID", by.y="row.names") %>%
#   ggplot() + geom_point(aes(x=ax1, y=ax3, color=transit.days, size=CH4))
# 
# 
# procuste(mgs_metadata_food %>% select(Patient_ID,contains("A", ignore.case = FALSE)) %>%
#   tibble::column_to_rownames("Patient_ID"), 
#     mgs_clades_pco$tab)$scorY %>%
#   merge(mgs_metadata_food[1:5],.,by.x="Patient_ID", by.y="row.names") %>%
#   ggplot() + geom_point(aes(x=transit.days, y=ax3, color=transit.days), size=4)
# 



procuste(mgs_metadata_food %>% select(Patient_ID,contains("A", ignore.case = FALSE)) %>%
  tibble::column_to_rownames("Patient_ID"), 
    mgs_clades_pco$tab)$scorY %>%
  merge(mgs_metadata_food[1:12],.,by.x="Patient_ID", by.y="row.names") %>%
  select(CH4,ax1) %>%
  na.omit %>%
  ggplot() + geom_histogram(aes(x=ax1, fill=CH4 %>% cut(b=c(-1,1,5,50))), bins = 3, position = "fill", color="black") +
  scale_fill_brewer("CH4 (ppm)", label = c("less than 1","from 1 to 5", "more than 5")) + scale_y_continuous(labels = scales::percent_format())
  



  
procuste(mgs_metadata_food %>% select(Patient_ID,contains("A", ignore.case = FALSE)) %>%
  tibble::column_to_rownames("Patient_ID"), 
    mgs_clades_pco$tab)$scorY %>%
  merge(mgs_metadata_food[1:12],.,by.x="Patient_ID", by.y="row.names") %>%
  select(transit.days,ax3) %>%
  na.omit %>%
  ggplot() + 
  geom_histogram(aes(x=ax3,  fill=transit.days %>% cut(b=c(0,1,2,3,6))), bins = 3, position = "fill", color="black") +
  scale_fill_brewer("transit (days)", label = c("less than 1","from 1 to 2", "from 2 to 3", "more than 3"), palette = 3) + scale_y_continuous(labels = scales::percent_format())





```



## IBS severity signature vs Food OTU



```{r}


cag_severe = system.file("CAG", "IBS_severity_mgs_clades_prop.csv", package="IBSFood") %>% read.csv2(row.names=1)



cag_sev_jsd = 
  cag_severe[intersect(colnames(OTU), colnames(t(cag_severe))),-1] %>% 
  as.data.frame %>% 
  t %>%
  BiotypeR::dist.JSD()

food_unifrac_select_severe = 
food_unifrac %>% 
  as.matrix %>%
  .[intersect(colnames(OTU), colnames(t(cag_severe))),intersect(colnames(OTU), colnames(t(cag_severe)))] %>% 
  as.dist



cag_sev_jsd_pco = dudi.pco(cag_sev_jsd, scannf=F, nf=3)

food_unifrac_select_severe_pco  = dudi.pco(food_unifrac_select_severe %>% ade4::quasieuclid(), scannf=F, nf=3)
mic_food_coi = coinertia(cag_sev_jsd_pco, food_unifrac_select_severe_pco, scannf=F, nf=3)

mic_food_coi %>% plot



 cor(procuste(food_unifrac_select_severe_pco$tab, cag_sev_jsd_pco$tab)$scorX[,1:4],
     cbind(
       t(OTU)[colnames(cag[,intersect(colnames(OTU), colnames(t(cag_severe)))]),],
       t(OTU_lvl3)[colnames(cag[,intersect(colnames(OTU), colnames(t(cag_severe)))]),],
       t(OTU_lvl2)[colnames(cag[,intersect(colnames(OTU), colnames(t(cag_severe)))]),],
       t(OTU_lvl1)[colnames(cag[,intersect(colnames(OTU), colnames(t(cag_severe)))]),]
           
       ),
    
     
     
      method="spearman"
       ) %>% t %>% as.data.frame %>% tibble::rownames_to_column() %>% arrange(desc(abs(ax1))) %>%
 na.omit() %>% 
   filter(abs(ax1) > 0.3 | abs(ax2) > 0.3) -> b
 
 



 cor(procuste(food_unifrac_select_severe_pco$tab, cag_sev_jsd_pco$tab)$scorY[,1:4],
     t(cag_severe[intersect(colnames(OTU), colnames(t(cag_severe))),-1] %>% 
  as.data.frame %>% 
  t),
     method="spearman"
       ) %>% t %>% as.data.frame %>% tibble::rownames_to_column() %>% arrange(desc(abs(ax1))) %>% 
   na.omit() %>% 
   filter(abs(ax1) > 0.3 | abs(ax2) > 0.3) %>%
   #separate(col=rowname, sep="_", into=c("domain","phylum","order","class","family","genus")) %>%
     ggplot() + 
   geom_point(aes(x=ax1, y=ax2)) + ggrepel::geom_text_repel(aes(x=ax1, y=ax2, label=rowname)) + 
   geom_point(data=b, aes(x=ax1, y=ax2)) +  ggrepel::geom_text_repel(data=b, aes(x=ax1, y=ax2, label=rowname))
 
 
procuste.randtest(food_unifrac_select_severe_pco$tab, cag_sev_jsd_pco$tab)


```


### link with metadata
```{r, message=FALSE, warning=FALSE}



procuste(mgs_metadata_food %>% select(Patient_ID,contains("A", ignore.case = FALSE)) %>%
  tibble::column_to_rownames("Patient_ID"), 
    cag_sev_jsd_pco$tab, nf = 10)$scorY %>%
  merge(mgs_metadata_food[1:12],.,by.x="Patient_ID", by.y="row.names") %>%
  melt(id.vars=c(paste0("ax",1:10),"Patient_ID","Health","SSgroup")) %>%
  melt(id.vars=c("Patient_ID","Health","SSgroup","variable","value"), variable.name = "axis", value.name = "coord") %>%       
  group_by(variable,axis) %>%
  na.omit %>% do(broom::tidy(cor.test(.$value, .$coord, method="spearman"))) %>%
  arrange((p.value))



 cor(procuste(food_unifrac_select_severe_pco$tab, cag_sev_jsd_pco$tab)$scorX[,1:4],
     cbind(
       t(OTU)[colnames(cag[,intersect(colnames(OTU), colnames(t(cag_severe)))]),],
       t(OTU_lvl3)[colnames(cag[,intersect(colnames(OTU), colnames(t(cag_severe)))]),],
       t(OTU_lvl2)[colnames(cag[,intersect(colnames(OTU), colnames(t(cag_severe)))]),],
       t(OTU_lvl1)[colnames(cag[,intersect(colnames(OTU), colnames(t(cag_severe)))]),]
           
       ),
    
     
     
      method="spearman"
       ) %>% t %>% as.data.frame %>% tibble::rownames_to_column() %>% arrange(desc(abs(ax1))) %>%
 na.omit() %>% 
   filter(abs(ax1) > 0.3 | abs(ax3) > 0.3) -> b
 
 




 cor(procuste(food_unifrac_select_severe_pco$tab, cag_sev_jsd_pco$tab)$scorY[,1:4],
     t(cag_severe[intersect(colnames(OTU), colnames(t(cag_severe))),-1] %>% 
  as.data.frame %>% 
  t),
     method="spearman"
       ) %>% t %>% as.data.frame %>% tibble::rownames_to_column() %>% arrange(desc(abs(ax1))) %>% 
   na.omit() %>% 
   filter(abs(ax1) > 0.3 | abs(ax3) > 0.3) %>%
   #separate(col=rowname, sep="_", into=c("domain","phylum","order","class","family","genus")) %>%
     ggplot() + 
   geom_point(aes(x=ax1, y=ax3)) + ggrepel::geom_text_repel(aes(x=ax1, y=ax3, label=rowname)) + 
   geom_point(data=b, aes(x=ax1, y=ax3)) +  ggrepel::geom_text_repel(data=b, aes(x=ax1, y=ax3, label=rowname))
 
 





```




