---
title: "MSP Infraspecies association with nutrient and foods"
output: html_notebook
---

## load library

```{r}
library(ade4)
library(dplyr)
library(magrittr)
library(ggplot2)
devtools::load_all()


```


## load infraspecies data table
```{r}

infraspecies = readr::read_csv2(system.file("infraspecies", "infraspecies_table_full.csv", package="IBSFood"))[,-1]




```

## correlation analyis

```{r}


rbind(
infraspecies %>%
  mutate_at(vars(contains("M", ignore.case = F)),function(x){x/sum(x)}) %>%
  select(contains("M", ignore.case = F),phylum) %>%
  group_by(phylum) %>%
  summarise_all(sum) %>%
  reshape2::melt(id.vars="phylum") %>%
  mutate(taxa = "phylum") %>%
  rename(tax_variable = phylum),


infraspecies %>%
  mutate_at(vars(contains("M", ignore.case = F)),function(x){x/sum(x)}) %>%
  select(contains("M", ignore.case = F),phylum,family) %>%
  group_by(phylum,family) %>%
  summarise_all(sum) %>%
  ungroup() %>%
  select(-phylum) %>%
  reshape2::melt(id.vars="family")%>%
  mutate(taxa = "family") %>%
  rename(tax_variable = family),


infraspecies %>%
  mutate_at(vars(contains("M", ignore.case = F)),function(x){x/sum(x)}) %>%
  select(contains("M", ignore.case = F),phylum,family,genus) %>%
  group_by(phylum,family,genus) %>%
  summarise_all(sum) %>%
  ungroup() %>%
  select(-phylum,-family) %>%
  reshape2::melt(id.vars="genus") %>%
  mutate(taxa = "genus") %>%
  rename(tax_variable = genus),


infraspecies %>%
  mutate_at(vars(contains("M", ignore.case = F)),function(x){x/sum(x)}) %>%
  select(contains("M", ignore.case = F),phylum,family,genus,msp_name) %>%
  group_by(phylum,family,genus,msp_name) %>%
  summarise_all(sum) %>%
  ungroup() %>%
  select(-phylum,-family,-genus) %>%
  reshape2::melt(id.vars="msp_name") %>%
  mutate(taxa = "MSP") %>%
  rename(tax_variable = msp_name),


infraspecies %>%
  mutate_at(vars(contains("M", ignore.case = F)),function(x){x/sum(x)}) %>%
  select(contains("M", ignore.case = F),phylum,family,genus,msp_name, msp_name_partition) %>%
  group_by(phylum,family,genus,msp_name, msp_name_partition) %>%
  summarise_all(sum) %>%
  ungroup() %>%
  select(-phylum,-family,-genus, -msp_name) %>%
  reshape2::melt(id.vars="msp_name_partition") %>%
  mutate(taxa = "Infraspecies") %>%
  rename(tax_variable = msp_name_partition)
) -> compo_taxa_melt


compo_taxa_melt %>% head

```





### load nutrient data
```{r}
data("nutrients_data")

nutrients_data %>%
  reshape2::melt(id.vars="ID") %>%
  merge(.,compo_taxa_melt, by.y="variable", by.x="ID") -> compo_taxa_nutrient_melt
  


compo_taxa_nutrient_melt %>% 
  #filter(variable == "Niek _mg" | tax_variable == "msp_1265_unassigned" | tax_variable =="msp_0849_cl_1"| tax_variable == "msp_0849") %>%
  group_by(taxa,tax_variable,variable) %>%
  summarize(cor = cor(value.x,value.y, method="spearman")) -> nutrient_taxa_cor
  
write.csv2(nutrient_taxa_cor, file="nutrient_taxa_cor.csv")

nutrient_taxa_cor %>%
  ggplot() + geom_density(aes(x=abs(cor), fill=taxa), alpha=0.5)


```


### analysis
```{r}


infraspecies %>% 
  mutate_at(vars(contains("M", ignore.case = F)),function(x){x/sum(x)}) %>%
  select(contains("M", ignore.case = F), msp_name_partition) %>%
  tibble::column_to_rownames("msp_name_partition") %>%
  t %>% as.data.frame() %>%
  merge(.,nutrients_data, by.x="row.names", by.y="ID") -> infraspecies_nutrient_df



infraspecies %>% 
  mutate_at(vars(contains("M", ignore.case = F)),function(x){x/sum(x)}) %>%
  select(contains("M", ignore.case = F), msp_name) %>%
  group_by(msp_name) %>%
  summarise_at(vars(contains("M", ignore.case = F)),sum) %>%
  tibble::column_to_rownames("msp_name") %>%
  t %>% as.data.frame() %>%
  merge(.,nutrients_data, by.x="row.names", by.y="ID") -> MSP_nutrient_df



dim(infraspecies_nutrient_df)
dim(MSP_nutrient_df)


dim(nutrients_data)


cor(log10(infraspecies_nutrient_df[2:(1838-49)]+10^-6),infraspecies_nutrient_df[(1838-48):1838], method="pearson") %>% 
  reshape2::melt() %>%
  filter(abs(value) > 0.5) %>%
  merge(.,infraspecies %>% select(species, msp_name, msp_name_partition), by.x="Var1", by.y="msp_name_partition") %>% select(-msp_name) %>%
  arrange(desc(abs(value)))



cor(log10(MSP_nutrient_df[2:(1481-49)]+10^-6),MSP_nutrient_df[(1481-48):1481], method="pearson") %>% 
  reshape2::melt() %>%
  filter(abs(value) > 0.5) %>%
  merge(.,infraspecies %>% select(species, msp_name), by.x="Var1", by.y="msp_name") %>%
  arrange(desc(abs(value)))



```

## compute MSP infraspecies distance matrix

```{r}

infraspecies_jsd = BiotypeR::dist.JSD(infraspecies %>% 
                                        mutate_at(vars(contains("M", ignore.case = F)),function(x){x/sum(x)}) %>% select(contains("M",ignore.case = F)))

save(infraspecies_jsd, file="infraspecies_jsd")


tre = system.file("biom", "infraspecies.tree", package="IBSFood")


infraspecies.tree = ape::read.tree(file=tre)

infraspecies.tree$edge.length = rep(1, dim(infraspecies.tree$edge)[1]) #important to add edge length to compute unifrac distance

TAX = phyloseq::tax_table(infraspecies %>%
              select(superkingdom, phylum, class, order, family, genus, species, msp_name, msp_name_partition) %>%
              unique %>%
              na.omit() %>%
             tibble::column_to_rownames("msp_name_partition")%>% as.matrix)


OTU = phyloseq::otu_table(infraspecies %>% select(contains("M", ignore.case = F),msp_name_partition) %>% tibble::column_to_rownames("msp_name_partition")%>% as.matrix, taxa_are_rows = TRUE)
OTU = OTU %>% multiply_by(50*10^6) %>% round() 

physeq=phyloseq::phyloseq(OTU,TAX,infraspecies.tree)


phyloseq::phy_tree(physeq) <- ape::root(phy=phyloseq::phy_tree(physeq), outgroup="msp_0001_unassigned", resolve.root=TRUE, interactive=FALSE) #outgroup is an eucaryote

save(physeq, file="infraspecies_phyloseq")

infraspecies_unifrac = phyloseq::distance(physeq, method="unifrac")

save(infraspecies_unifrac, file="infraspecies_unifrac")
load("infraspecies_unifrac")
#infraspecies_jsd_phyloseq = phyloseq::distance(physeq, method="jsd")
# 
# infraspecies %>%
#   select(superkingdom, msp_name_partition) %>%
#   filter(superkingdom == "Eukaryota")
# 

```


## co-inertia analysis

```{r}

load(system.file("biom", "food_unifrac.dist", package="IBSFood"))

A = merge(infraspecies_unifrac %>% broom::tidy(diagonal=TRUE, upper=TRUE),
food_unifrac %>% broom::tidy(diagonal=TRUE, upper=TRUE) , by=c("item1","item2")) %>%
  reshape2::dcast(item1~item2, value.var = "distance.x") %>% .[,-1] %>%
  as.dist()

B = merge(infraspecies_unifrac %>% broom::tidy(diagonal=TRUE, upper=TRUE),
food_unifrac %>% broom::tidy(diagonal=TRUE, upper=TRUE) , by=c("item1","item2")) %>%
  reshape2::dcast(item1~item2, value.var = "distance.y") %>% .[,-1] %>%
  as.dist()


infraspecies_pco = dudi.pco(A %>% ade4::quasieuclid(), scannf = F, nf=3)

food_pco = dudi.pco(B %>% ade4::quasieuclid(), scannf = F, nf=10)


infraspecies_food_coi = coinertia(infraspecies_pco,food_pco, scannf=F, nf=10)


plot(infraspecies_food_coi)


coinertia(dudi.pca(infraspecies_pco$li, scannf=F, nf=3),dudi.pca(food_pco$li, scannf=F, nf=3), scannf=F, nf=3) %>% randtest


```

### compute correlation with co-inertia component

```{r}


infraspecies_food_coi$lX %> head



infraspecies %>% 
  select(contains("M", ignore.case = F),msp_name_partition) %>%
  mutate_at(vars(contains("M", ignore.case = F)),function(x){x/sum(x)}) %>%
  reshape2::melt(id.vars="msp_name_partition") %>%
  merge(infraspecies_food_coi$lX,.,by.x="row.names", by.y="variable") %>%
  group_by(msp_name_partition) %>%
  summarize(A1_cor=cor(AxcX1,value, method="spearman"), 
            A2_cor=cor(AxcX2,value, method="spearman"),
            A3_cor=cor(AxcX3,value, method="spearman")) %>%
  filter(abs(A1_cor)> 0.25|abs(A2_cor)> 0.25 ) %>%
  arrange(msp_name_partition) -> infraspecies_coi_cor








```


```{r}
data("food_data")
data("food_group_levels")

food_data %>%
  merge(food_group_levels, by.x="Code",by.y="Livsmedelsnummer", all = FALSE) %>%
  select(-Foodstuffs.y) %>%
  dplyr::rename(Foodstuffs = Foodstuffs.x) %>%
  group_by(Identity, `Food groups lvl1`, `Food groups lvl2`, `Food groups lvl3`,`Food groups lvl4`) %>%
  summarise(Gram = sum(Gram)) %>%
  na.omit() %>%
  reshape2::dcast(Identity ~ `Food groups lvl4`, value.var = "Gram",fill = 0 ) %>%
    tibble::column_to_rownames("Identity") %>%
  t() %>%
  #as_tibble %>%
  round() -> food_otu

infraspecies_food_coi$lY %>% head


food_otu %>% 
  reshape2::melt() %>%
  #reshape2::melt(id.vars="msp_name_partition") %>%
  merge(infraspecies_food_coi$lY,.,by.x="row.names", by.y="Var2") %>%
  group_by(Var1) %>%
  summarize(A1_cor=cor(AxcY1,value, method="spearman"), 
            A2_cor=cor(AxcY2,value, method="spearman"),
            A3_cor=cor(AxcY3,value, method="spearman")) %>%
  filter(abs(A1_cor)> 0.25|abs(A2_cor)> 0.25 ) %>% arrange(A2_cor) -> food_coi_cor




```


```{r}

food_group_levels %>%
  select(-Livsmedelsnamn, -Livsmedelsnummer, -Livsmedelsnamn_eng, -Foodstuffs) %>% 
  unique %>%
  arrange(`Food groups lvl4`)



```

## association with metadata

```{r}



infraspecies_food_coi$lX[1:3] %>%
  merge(.,IBSMicrobiota::IBSData$metadata %>%
          filter(Visit=="V4",Sample_type=="Stool"), by.x="row.names", by.y="Patient_ID") %>%
  select_if(is.numeric) %>%
  mutate(H2_CH4 = H2/(CH4+1)) %>%
  reshape2::melt(id.vars=c("AxcX1","AxcX2","AxcX3")) %>%
  group_by(variable) %>%
  na.omit() %>%
  
  summarise(A1_cor =  cor(AxcX1, value, method = "spearman")     %>% round(2),
            A1_p   =  cor.test(AxcX1, value, method = "spearman")$p.value %>% round(2),
            A2_p   =  cor.test(AxcX2, value, method = "spearman")$p.value %>% round(2),
            A2_cor =  cor(AxcX2, value, method = "spearman")     %>% round(2),
            #A3_cor=  cor.test(AxcX3, value, method = "spearman")$p.value %>% round(2),
            n=n())


infraspecies_food_coi$lX[1:3] %>%
  merge(.,IBSMicrobiota::IBSData$metadata %>%
          filter(Visit=="V4",Sample_type=="Stool"), by.x="row.names", by.y="Patient_ID") %>%
  mutate(breath_H2 = ifelse(H2>5,"High_H2","Low_H2"), breath_CH4 = ifelse(H2>5,"High_CH4","Low_CH4")) %>%
  ggplot() + geom_point(aes( y=AxcX2, x=(H2+1)/(CH4+1) %>% log2))  + geom_smooth(aes( y=AxcX2, x=(H2+1)/(CH4+1) %>% log2), method = "lm")



infraspecies_food_coi$lX[1:3] %>%
  merge(.,IBSMicrobiota::IBSData$metadata %>%
          filter(Visit=="V4",Sample_type=="Stool"), by.x="row.names", by.y="Patient_ID") %>%
  mutate(breath_H2 = ifelse(H2>10,"High_H2","Low_H2"), breath_CH4 = ifelse(CH4>10,"High_CH4","Low_CH4")) %>%
  ggplot() + geom_boxplot(aes( y=AxcX2, x=paste(breath_H2,breath_CH4))) + coord_flip()


```

## visualisations

```{r}

infraspecies_coi_cor %>%
  merge(.,infraspecies %>% select(-contains("M",ignore.case = F)), by="msp_name_partition") %>%
  #filter(abs(A1_cor)>0.35|abs(A2_cor)>0.35) %>% 
  arrange(A1_cor)


infraspecies_coi_cor %>%
  merge(.,infraspecies %>% select(-contains("M",ignore.case = F)), by="msp_name_partition") %>%
  filter(abs(A1_cor)>0.35|abs(A2_cor)>0.35) %>%
  ggplot() + ggrepel::geom_label_repel(aes(x=A1_cor, y=A2_cor, label=genus), size=2, label.size = NA, fill=NA)



infraspecies_coi_cor %>%
  merge(.,infraspecies %>% select(-contains("M",ignore.case = F)), by="msp_name_partition") %>%
  filter(abs(A1_cor)>0.35|abs(A2_cor)>0.35) %>%
  ggplot() + ggrepel::geom_label_repel(aes(x=A1_cor, y=A2_cor, label=msp_name_partition), size=2, label.size = NA, fill=NA)



```


```{r}

food_coi_cor %>%
  merge(food_group_levels %>%
  select(-Livsmedelsnamn, -Livsmedelsnummer, -Livsmedelsnamn_eng, -Foodstuffs) %>% 
  unique %>%
  arrange(`Food groups lvl4`), by.x="Var1", by.y="Food groups lvl4") %>%
  filter(abs(A1_cor)>0.35|abs(A2_cor)>0.35) %>%
  ggplot() + ggrepel::geom_label_repel(aes(x=A1_cor, y=A2_cor, label=`Food groups lvl3`), size=2, label.size = NA, fill=NA)




```

