---
title: "study cohort summary table"
output: html_notebook
---


##load library
```{r}

library(dplyr)
library(IBSMicrobiota)
devtools::load_all()



```

## load data
```{r}

data("food_data")

data("IBSData")

data("genes_richness_1M")


subject_metaG = genes_richness_1M %>% row.names()

subject_food = food_data %>% .$Identity %>% unique


c(subject_metaG,subject_food) %>% unique %>% length

intersect(subject_metaG,subject_food) %>% unique %>% length


```


### load raw data
```{r}

study_cohort_global_metadata =

readxl::read_xlsx(system.file("data-raw/MOSAIC food groups.xlsx", package="IBSFood"), sheet = 2) %>%
  select(1,2,3,4,`IBS Severity Score`) %>%
  dplyr::rename(Patient_ID=`Pat.nr`, Health=Patient) %>%
  mutate(Health=ifelse(Health==1,"patient","control"), Gender=ifelse(Gender==1,"F","M")) %>%
  mutate(SSgroup =  case_when(`IBS Severity Score` <= 175 ~ "mild",
                              `IBS Severity Score` <= 300 ~ "moderate",
                              `IBS Severity Score` > 300 ~ "severe")) %>%
  mutate(SSgroup = ifelse(Health=="control", "control",SSgroup))
  

# 
# study_cohort_global_metadata =
#   
# readxl::read_xlsx(system.file("data-raw/MOSAIC food groups.xlsx", package="IBSFood"), sheet = 3) %>%
#   select(1,BMI) %>%
#   mutate(ID=ID%>%gsub(" ,3d", "", .)) %>%
#   merge(study_cohort_global_metadata,., by.y="ID", by.x="Patient_ID", all.x=TRUE) 
#   

study_cohort_global_metadata =
  
readxl::read_xlsx(system.file("data-raw/lactulose_ibs_metadata.xlsx", package="IBSFood"), sheet = 2) %>%
  select(Patient_ID,Height, Weight, BMI, H2,CH4,`IBS_subtype_docvisit..1.IBS.C..2.IBS.D..3.IBS.M..4.IBS.U.`, `HAD.ANXIETY`, `HAD.DEPRES`) %>%
  mutate(BMI  =  BMI %>% as.numeric, H2 = H2 %>% as.numeric, CH4 = CH4 %>% as.numeric) %>%
  dplyr::rename(IBS_subtype = `IBS_subtype_docvisit..1.IBS.C..2.IBS.D..3.IBS.M..4.IBS.U.`) %>%
  merge(study_cohort_global_metadata,., by="Patient_ID", all.x=TRUE) 




```




```{r}

study_global_metadata = 

study_cohort_global_metadata %>%
  select(Patient_ID,Health,Gender,Age, BMI,SSgroup, `IBS Severity Score`, H2, CH4, IBS_subtype, HAD.ANXIETY, HAD.DEPRES) %>%
  arrange(Patient_ID) %>%
  unique() %>%
  filter(Patient_ID %in% unique(c(subject_metaG,subject_food))) %>%
  merge(data.frame(subject_metaG,metaG_data="Yes"),by.x="Patient_ID",by.y="subject_metaG", all.x = TRUE) %>%
  merge(data.frame(subject_food,food_data="Yes"),by.x="Patient_ID",by.y="subject_food", all.x = TRUE) %>%
  mutate(metaG_data = ifelse(is.na(metaG_data),"No",metaG_data %>% as.character),
         food_data = ifelse(is.na(food_data),"No",food_data %>% as.character))
           

write.csv2(study_global_metadata,file="study_global_metadata.csv")



merge(data.frame(subject_metaG,metaG_data="Yes"), data.frame(subject_food,food_data="Yes"), by.x="subject_metaG", by.y="subject_food", all = TRUE) %>% dim
  




```



```{r}

(study_global_metadata %>%
  mutate(SSgroup=SSgroup %>% as.character) %>%
  mutate(SSgroup=ifelse(is.na(SSgroup),"Unknown",SSgroup)) %>%
  mutate(Data= ifelse(metaG_data=="Yes" & food_data=="No","Microbiota only",ifelse(metaG_data=="No" & food_data=="Yes","Food only", "both") )) %>%
  group_by(Health) %>%
  summarise(n=n(),
            Female = sum(Gender=="F"),
            Male = sum(Gender=="M"),
            Age_median=median(Age),
            Age_q25=quantile(Age,0.25),
            Age_q75=quantile(Age,0.75),
            BMI_median=median(BMI, na.rm=TRUE),
            BMI_q25=quantile(BMI,0.25,na.rm=TRUE),
            BMI_q75=quantile(BMI,0.75, na.rm=TRUE),
            Mild=sum(SSgroup=="mild"),
            Moderate=sum(SSgroup=="moderate"),
            Severe=sum(SSgroup=="severe"),
            Microbiota_only= sum(Data=="Microbiota only"),
            Food_only=sum(Data=="Food only"),
            Both=sum(Data=="both")
            
            ) %>% 
  as.data.frame %>%
  tibble::column_to_rownames("Health") %>% t %>% as.data.frame -> study_summary_metadata)


write.csv2(study_summary_metadata,file="study_summary_metadata.csv")

```

